### ISSUE TITLE
Doesn't parse loud comments (/*!)

### ISSUE THREAD

**Issue by strarsis** [syavorsky/comment-parser#124] opened 2021-03-23 13:11 UTC
Apparently the parser skips loud comments (as tried in playground):
`/*!` is a loud CSS comment which is not parsed by the parser in the parser playground.

Or have I misunderstood its purpose and it is actually only parsing comments with an extra star (`/**`)?
Can I reconfigure it so I can use it with normal (and loud) CSS comments?

**Comment by syavorsky** [comment] 2021-03-23 18:02
yeah, that's how it is now. Probably, I should have described it better in the README
> And it can be used with any language supporting /** */ source comments.

#97 suggests implementing custom markers, that might possibly fit, but there is nothing done to make it happen yet

**Comment by syavorsky** [comment] 2021-03-31 19:30
duplicate of #97

**Closed by syavorsky** 2021-03-31 19:30 UTC
